# -*- coding: utf-8 -*-
"""
/***************************************************************************
 czech_land_use_and_CN_Analyzer
                                 A QGIS plugin
 czech_land_use_and_CN_Analyzer
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-19
        copyright            : (C) 2024 by CTU
        email                : jehlijos@cvut.cz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load czech_land_use_and_CN_Analyzer class from file czech_land_use_and_CN_Analyzer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .czech_land_use_and_CN_Analyzer import czech_land_use_and_CN_Analyzer
    return czech_land_use_and_CN_Analyzer(iface)
