land_use:
  - keywords: [Travní, travní, Travni, travni]
    code: 20000
  - keywords: [Lesní, lesní, Lesni, lesni]
    code: 32100 # platí pro Lesní průsek a Lesní půdu s křovinatým porostem
  - keywords: [Kosodřevinou, kosodřevinou, Kosodrevinou, kosodrevinou]
    code: 32200
  - keywords: [Skalní, skalní, Skalni, skalni]
    code: 82100
  - keywords: [Budova, budova, budov, Budov]
    code: 41000
  - keywords: [Věž, věž, Vez, vez]
    code: 41000
  - keywords: [Nadrz, nadrz, Nádrž, nádrž]
    code: 41000 # Platí pro Nadzemní zásobní nádrž. Dále pro Pozemní nádrž - později přepsáno
  - keywords: [Hrad , hrad ]
    code: 41000    
  - keywords: [Zamek, zamek, zámek, Zámek]
    code: 41000
  - keywords: [Tribuna, tribuna]
    code: 41000 
  - keywords: [Parkoviste, parkoviste, parkoviště, Parkoviště]
    code: 42100 
  - keywords: [Trať, trať, trat, Trat]
    code: 42300 
  - keywords: [Kolejiste, kolejiště, kolejiste, Kolejiště]
    code: 42300
  - keywords: [Silnice, slinice]
    code: 42100 
  - keywords: [Chmelnice, chmelnice]
    code: 52000
  - keywords: [Vinice, vinice]
    code: 51000 
  - keywords: [Rozvodna, rozvodna]
    code: 46100 
  - keywords: [Hřbitov, Hrbitov, hrbitov, hřbitov]
    code: 43300
  - keywords: [Skleník, sklenik, Sklenik, skleník]
    code: 41000
  - keywords: [Bažina, bazina, Bazina, bažina]
    code: 73000
  - keywords: [liniova, Liniova, Liniová, liniová]
    code: 61200   
  - keywords: [raseliniste, rašeliniště, Raseliniste, Rašeliniště]
    code: 74000   
  - keywords: [precerpavaci, přečerpávací, Precerpavaci, Přečerpávací]
    code: 46200   
  - keywords: [Sidlech, sidlech, sídlech, Sídlech]
    code: 46300
  - keywords: [Letiste, letiste, letiště, Letiště]
    code: 23100
  - keywords: [sesuv, Sesuv]
    code: 82200
  - keywords: [Vlečka, vlecka, vlečka, Vlecka]
    code: 42300
