URI: https://ags.cuzk.cz/arcgis/services/ZABAGED_POLOHOPIS/MapServer/WFSServer

# This list contains buffer options, values in controlling_atr_name change length of buffers for point/line objects. Distance is in meters.
buffer_layers:
  - input_layer_name: "ZABAGED_POLOHOPIS:Silnice__dálnice"
    controlling_atr_name: "typsil_k"
    buffer_levels:
      - priority: "1"
        values: ["D1", "D2"]
        distance: 18
      - priority: "4"
        values: ["M"]
        distance: 15
      - priority: "2"
        values: ["D1p", "D2p"]
        distance: 9
      - priority: "3"
        values: ["D1v", "D2v"]
        distance: 9
      - priority: "5"
        values: ["Mp", "Mv"]
        distance: 7.5
      - priority: "6"
        values: ["S1"]
        distance: 7
      - priority: "7"
        values: ["S2"]
        distance: 5
      - priority: "8"
        values: ["S3"]
        distance: 4
      - priority: "6"
        values: ["S1v", "S1p"]
        distance: 3.5
      - priority: "7"
        values: ["S2v", "S2p"]
        distance: 2.5
      - priority: "8"
        values: ["S3v", "S3p"]
        distance: 2.0
    default_buffer: 4

  - input_layer_name: "ZABAGED_POLOHOPIS:Silnice_ve_výstavbě"
    controlling_atr_name: "NaN"
    default_buffer: 5.5

  - input_layer_name: "ZABAGED_POLOHOPIS:Silnice_neevidovaná"
    controlling_atr_name: "NaN"
    default_buffer: 2.5

  - input_layer_name: "ZABAGED_POLOHOPIS:Ulice"
    controlling_atr_name: "typulice_k"
    buffer_levels:
      - priority: "1"
        values: ["026", "926"] # US, USm - ulice sjízdná v sídle a mimo sídlo
        distance: 3.0
      - priority: "2"
        values: ["225"] # Uch - ulice typu chodník
        distance: 2.0
      - priority: "3"
        values: ["025"] # UN - ulice nesjízdná v sídle
        distance: 1.5
      - priority: "4"
        values: ["925"] # UNm - ulice nesjízdná mimo sídlo
        distance: 1.0
      - priority: "5"
        values: ["125"] # UX - ulice neexistující v terénu
        distance: 0.0
    default_buffer: 2.0

  - input_layer_name: "ZABAGED_POLOHOPIS:Cesta"
    controlling_atr_name: "typcesty_k"
    buffer_levels:
      - priority: "1"
        values: ["026"]  # cesta udržovaná
        distance: 2.0
      - priority: "3"
        values: ["025"]  # cesta neudržovaná
        distance: 1.0
      - priority: "2"
        values: ["099"]  # cesta parková a hřbitovní
        distance: 1.25
    default_buffer: 1.5
    
  - input_layer_name: "ZABAGED_POLOHOPIS:Liniová_vegetace"
    controlling_atr_name: "TYPVEG_K"
    buffer_levels:
      - priority: "1"
        values: ["S"] # stromořadí
        distance: 2.5
      - priority: "2"
        values: ["Z"] # živý plot
        distance: 0.0
    default_buffer: 2.5
 
  - input_layer_name: "ZABAGED_POLOHOPIS:Lesní_průsek"
    controlling_atr_name: "NaN"
    default_buffer: 0.0
    
  - input_layer_name: "ZABAGED_POLOHOPIS:Železniční_trať"
    controlling_atr_name: "NaN"
    default_buffer: 2.5
    
  - input_layer_name: "ZABAGED_POLOHOPIS:Železniční_vlečka"
    controlling_atr_name: "NaN"
    default_buffer: 2.5

# This list contains settings for ZABAGED layers where their LandUse code is updated by some value in its attribute.
# base_use_code is the LandUse code for the whole layer, and numbers from values in the controlling attribute are added to base_use_code.
layers:
  - name: "ZABAGED_POLOHOPIS:Areál_účelové_zástavby"
    base_use_code: 20000
    controlling_attribute: "typzast_k"
    value_increments:
      "101": 26200  # 46.200 ~ hlubinná těžba - bez omezení
      "102": 26200  # 46.200 ~ strojírenský průmysl - plocha ≥ 5 000 m2
      "103": 26200  # 46.200 ~ chemický průmysl - plocha ≥ 5 000 m2
      "104": 26200  # 46.200 ~ textilní, oděvní a kožedělný průmysl - plocha ≥ 5 000 m2
      "105": 26200  # 46.200 ~ průmysl skla, keramiky a staveb. hmot - plocha ≥ 5 000 m2
      "106": 26200  # 46.200 ~ potravinářský průmysl - plocha ≥ 5 000 m2
      "107": 26200  # 46.200 ~ dřevozpracující a papírenský průmysl - plocha ≥ 5 000 m2
      "108": 26200  # 46.200 ~ polygrafický průmysl - plocha ≥ 5 000 m2
      "109": 26200  # 46.200 ~ hutnický průmysl - plocha ≥ 5 000 m2
      "110": 26200  # 46.200 ~ ostatní, nerozlišený průmysl - plocha ≥ 5 000 m2
      "111": 26100  # 46.100 ~ chov hospodářských zvířat - plocha ≥ 5 000 m2
      "112": 26100  # 46.100 ~ zemědělský areál ostatní - plocha ≥ 5 000 m2
      "113": 26100  # 46.100 ~ skleníkové pěstování plodin - plocha ≥ 5 000 m2
      "201": 23100  # 43.100 ~ areál hradu (zřícenin) - bez omezení
      "202": 23100  # 43.100 ~ areál zámku - bez omezení
      "203": 41200  # 61.200 ~ archeologické naleziště - bez omezení
      "204": 23100  # 43.100 ~ hvězdárna - bez omezení
      "205": 23100  # 43.100 ~ kostel - bez omezení
      "206": 23100  # 43.100 ~ klášter - bez omezení
      "207": 23100  # 43.100 ~ kulturní objekt ostatní - bez omezení
      "208": 26200  # 46.200 ~ muzeum - bez omezení
      "209": 23300  # 43.300 ~ letní scéna - bez omezení
      "210": 23100  # 43.100 ~ škola - bez omezení
      "211": 23300  # 43.300 ~ výstaviště - plocha ≥ 10 000 m2
      "212": 23200  # 43.200 ~ skanzen - bez omezení
      "213": 23200  # 43.200 ~ zoo, safari - bez omezení
      "214": 23200  # 43.200 ~ botanická zahrada - bez omezení
      "215": 23100  # 43.100 ~ školské zařízení - bez omezení
      "301": 23100  # 43.100 ~ sportovní areál - plocha ≥ 2 000 m2
      "302": 23100  # 43.100 ~ plavecký areál - bez omezení
      "303": 23100  # 43.100 ~ stadión - bez omezení
      "304": 3200   # 23.200 ~ dostihový areál, parkur - bez omezení
      "305": 23100  # 43.100 ~ auto-moto-cyklo areál - bez omezení
      "306": 3100   # 23.100 ~ golfový areál
      "307": 23100  # 43.100 ~ střelnice - bez omezení
      "308": 3100   # 23.100 ~ plochy pro SLZ
      "309": 23100  # 43.100 ~ koupaliště - bez omezení
      "310": 23100  # 43.100 ~ camping - plocha ≥ 5 000 m2
      "311": 23100  # 43.100 ~ hřiště - plocha ≥ 2 000 m2
      "312": 23100  # 43.100 ~ chatová kolonie - plocha ≥ 10 000 m2 nebo šířka ≥ 50m a délka ≥ 200m
      "313": 23100  # 43.100 ~ rekreační zástavba - plocha ≥ 5 000 m2
      "314": 3200   # 23.200 ~ kynologické cvičiště - bez omezení
      "315": 23100  # 43.100 ~ zábavní park - bez omezení
      "316": 23100  # 43.100 ~ zahrádkářská osada - bez omezení
      "401": 26300  # 46.300 ~ sklad, hangár - plocha ≥ 5 000 m2
      "402": 26300  # 46.300 ~ přístav - bez omezení
      "403": 26200  # 46.200 ~ depo - bez omezení
      "404": 26300  # 46.300 ~ technické služby - bez omezení
      "405": 23100  # 43.100 ~ úpravna vody - bez omezení
      "406": 26100  # 46.100 ~ čistírna odpadních vod - bez omezení
      "407": 23100  # 43.100 ~ vodojem zemní - bez omezení
      "408": 22100  # 42.100 ~ autobusové nádraží - bez omezení
      "409": 26300  # 46.300 ~ čerpací stanice pohonných hmot - bez omezení
      "410": 23100  # 43.100 ~ meteorologická stanice - bez omezení
      "411": 23100  # 43.100 ~ vysílač - bez omezení
      "412": 23300  # 43.300 ~ nemocnice - bez omezení
      "413": 23100  # 43.100 ~ další zdravotní a sociální zařízení - bez omezení
      "414": 23300  # 43.300 ~ věznice - bez omezení
      "415": 26200  # 46.200 ~ kasárny a vojenské objekty - bez omezení
      "416": 26300  # 46.300 ~ skupinové garáže - plocha ≥ 2 000 m2
      "417": 26200  # 46.200 ~ hasičská stanice, zbrojnice - bez omezení
      "418": 26200  # 46.200 ~ policejní areál - bez omezení      
 
  - name: "ZABAGED_POLOHOPIS:Areál_železniční_stanice__zastávky"
    base_use_code: 46000
    controlling_attribute: "TYP"
    value_increments:
      stanice: 300  # 46.300
      zastávka: 200  # 46.200
           
  - name: "ZABAGED_POLOHOPIS:Cesta"
    base_use_code: 42000
    controlling_attribute: "povrch_k"
    value_increments:
      H: 400 # 42.400 ~ nedostatečně zpevněný (tráva, hlína, písek, kamení)
      K: 400 # 42.400 ~ zpevněný (dřevěná, kovová, ostatní konstrukce)
      O: 300 # 42.300 ~ neurčeno
      P: 200 # 42.200 ~ zpevněný (panel, dlažba)
      T: 300 # 42.300 ~ zpevněný (nosný terén, štěrk, kalený povrch)
      Z: 100 # 42.100 ~ zpevněný (asfalt, beton)

  - name: "ZABAGED_POLOHOPIS:Elektrárna__plocha_"
    base_use_code: 20000
    controlling_attribute: "PODTYPEL_K"
    value_increments:
      "001": 26200 # 46.200 ~ vodní
      "002": 26200 # 46.200 ~ jaderná
      "003": 3100  # 23.100 ~ solární
      "005": 26200 # 46.200 ~ větrná
      "008": 26200 # 46.200 ~ parní
      "009": 26200 # 46.200 ~ paroplynová
      "010": 26300 # 46.300 ~ plynová a spalovací
      "011": 26200 # 46.200 ~ vodní přečerpávací
      "012": 26200 # 46.200 ~ ostatní alternativní

  - name: "ZABAGED_POLOHOPIS:Heliport"
    base_use_code: 42000
    controlling_attribute: "povrtlof_k"
    value_increments:
      Z: 100 # 42.100 ~ zpevněný (asfalt, beton)
      P: 200 # 42.200 ~ zpevněný (panel, dlažba)
      H: 300 # 42.300 ~ nedostatečně zpevněný (tráva, hlína, písek, kamení)
      S: 200 # 42.200 ~ smíšený (nejednotný povrch)

  #- name: "ZABAGED_POLOHOPIS:Lesní_půda_se_stromy_kategorizovaná__plocha_" # překlasifikováno, kódy neaktualizovány
  #  base_use_code: 30000
  #  controlling_attribute: "druh_k"
  #  value_increments:
  #    N: 1000 # bez dalšího určení
  #    J: 1300 # jehličnatý, bez dalšího určení
  #    L: 1100 # listnatý, bez dalšího určení
  #    S: 1200 # smíšený, bez dalšího určení 
  - name: "ZABAGED_POLOHOPIS:Lesní_půda_se_stromy_kategorizovaná__plocha_"
    base_use_code: 31000
    controlling_attribute: "vyska_k"
    value_increments:
      "0": 0   # 31.000 ~ bez určení
      "1": 210 # 31.210 ~ smíšené, do 2,5 m
      "2": 220 # 31.220 ~ smíšené, od 2,5 m do 8 m
      "3": 230 # 31.230 ~ smíšené, od 8 m do 20 m
      "4": 240 # 31.240 ~ smíšené, nad 20 m

  - name: "ZABAGED_POLOHOPIS:Obvod_letištní_dráhy"
    base_use_code: 42000
    controlling_attribute: "povrch_k"
    value_increments:
      N: 400 # 42.400 ~ nezpevněný
      Z: 100 # 42.100 ~ zpevněný

  - name: "ZABAGED_POLOHOPIS:Orná_půda_a_ostatní_dále_nespecifikované_plochy"
    base_use_code: 10000  
    controlling_attribute: "TYP_PUDY_K"
    value_increments:
      OR: 0   # 10.000 ~ orná půda ~ úzkoř. plodiny ve vrstevnicových řádcích s posklizňovými zbytky ve šp. hydr. podmínkách
      OSN: 50000 # 60.000 ~ ostatní dále nespecifikované plochy
   
  - name: "ZABAGED_POLOHOPIS:Ovocný_sad__zahrada"
    base_use_code: 20000  
    controlling_attribute: "TYP_PUDY_K"
    value_increments:
      OS: 33000  # 53.000 ~ ovocný sad
      OTK: 2000  # 22.000 ~ souvislý travní porost intenzivní, bez dalšího určení ~ 22.300
      ZA: 23100  # 43.100 ~ zahrada

  - name: "ZABAGED_POLOHOPIS:Povrchová_těžba__lom"
    base_use_code: 44000
    controlling_attribute: "DRUHTEZ_K"
    value_increments:
      "7": 300  # 44.300 ~ uhlí
      "13": 300 # 44.300 ~ cihlářská surovina
      "16": 100 # 44.100 ~ kámen
      "25": 300 # 44.300 ~ písek
      "27": 100 # 44.100 ~ rudy, radioaktivní suroviny
      "28": 200 # 44.200 ~ rašelina
      "36": 200 # 44.200 ~ štěrkopísek
      "37": 300 # 44.300 ~ keramické suroviny
      "38": 100 # 44.100 ~ vápenec, dolomit
      "39": 200 # 44.200 ~ ostatní nerudy
      
  - name: "ZABAGED_POLOHOPIS:Pozemní_nádrž"
    base_use_code: 72000  
    controlling_attribute: "PODTYPOB_K"
    value_increments:
      BA: 300 # 72.300 ~ bazén
      CV: 300 # 72.300 ~ čištění odpadních vod 
      OP: 100 # 72.100 ~ ostatní pozemní nádrž
      SA: 300 # 72.300 ~ sádka

  - name: "ZABAGED_POLOHOPIS:Rozvalina__zřícenina"
    base_use_code: 46000
    controlling_attribute: "podtypob_k"
    value_increments:
      R: 300  # 46.300 ~ rozvalina
      Z: 100  # 46.100 ~ zřícenina ostatní
      ZH: 300 # 46.300 ~ zřícenina hradu
      ZZ: 300 # 46.300 ~ zřícenina zámku
      
  - name: "ZABAGED_POLOHOPIS:Skládka"
    base_use_code: 45000  
    controlling_attribute: "PODTYPOB_K"
    value_increments:
      M: 200 # 45.200 ~ skládka materiálu
      O: 210 # 45.210 ~ skládka odpadu

  - name: "ZABAGED_POLOHOPIS:Udržovaná_zeleň"
    base_use_code: 43000
    controlling_attribute: "typ_pudy_k"
    value_increments:
      PO: 200  # 43.200 ~ park, okrasná zahrada
      UZ: 100  # 43.100 ~ ostatní udržovaná zeleň
      N: 100   # 43.100 ~ nezadáno/neznámo

  - name: "ZABAGED_POLOHOPIS:Ulice"
    base_use_code: 42000  
    controlling_attribute: "typulice_k"
    value_increments:
      "025": 200 # 42.200 ~ ulice nesjízdná v sídle
      "026": 100 # 42.100 ~ ulice sjízdná v sídle
      "926": 100 # 42.100 ~ ulice sjízdná mimo sídlo
      "925": 300 # 42.300 ~ ulice nesjízdná mimo sídlo
      "125": 0   # REMOVED ~ ulice neexistující v terénu
      "225": 200 # 42.200 ~ ulice typu chodník

  - name: "ZABAGED_POLOHOPIS:Úložné_místo"
    base_use_code: 40000  
    controlling_attribute: "podtypob_k"
    value_increments:
      D: 32400 # 72.400 ~ odkaliště
      H: 5100  # 45.100 ~ halda

  - name: "ZABAGED_POLOHOPIS:Vodní_plocha"
    base_use_code: 72000  
    controlling_attribute: "TYP_VP_K"
    value_increments:
      "1": 200 # 72.200 ~ přehradní nádrž
      "2": 100 # 72.100 ~ rybník
      "3": 100 # 72.100 ~ antropogenní jezero
      "4": 500 # 72.500 ~ jezero přírodního původu
      "5": 100 # 72.100 ~ výhonová tůně
      "6": 100 # 72.100 ~ koupaliště
      "7": 300 # 72.300 ~ rybniční sádka
      "8": 300 # 72.300 ~ sedimentační nádrž
      "9": 100 # 72.100 ~ ostatní vodní plocha
      "10": 100 # 72.100 ~ neurčená vodní plocha

  - name: "ZABAGED_POLOHOPIS:Železniční_točna__přesuvna"
    base_use_code: 40000  
    controlling_attribute: "TYPOBZEL_K"
    value_increments:
      TO: 2300 # 42.300 ~ točna
      PR: 1000 # 41.000 ~ přesuvna    