# .github/workflows/deploy.yml
name: Deploy MkDocs

# Trigger on pushes to main
on:
  push:
    branches: [ main ]

permissions:
  contents: write       # allows pushing to gh-pages

# Set defaults for all runs in every job
defaults:
  run:
    working-directory: ./docs  # run all steps from docs/ :contentReference[oaicite:0]{index=0}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # checks out your repo :contentReference[oaicite:1]{index=1}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: pip install mkdocs mkdocs-material
      - run: mkdocs gh-deploy --force --clean
        # uses the local mkdocs.yml by default :contentReference[oaicite:2]{index=2}
